// ImageGen monkey boss and desktop tree interactions stay cosmetic.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'shell/app.js'),'utf8');
const png=fs.readFileSync(path.join(root,'shell/assets/monkey-banana-2026-09-07/gold-chain-monkey.png'));
const css=fs.readFileSync(path.join(root,'shell/styles.css'),'utf8');
const html=fs.readFileSync(path.join(root,'shell/index.html'),'utf8');
const elements=new Map();
const $=id=>{if(!elements.has(id))elements.set(id,{dataset:{},removeAttribute(name){delete this.dataset[name.replace('data-','')];}});return elements.get(id);};
let reduced=false,nextId=0;
const timers=new Map();
const state={petInteractionToken:0,petInteractionTimer:null,petInteractionResolve:null};
const ctx={state,$,window:{matchMedia:()=>({matches:reduced}),setTimeout:fn=>{timers.set(++nextId,fn);return nextId;},clearTimeout:id=>timers.delete(id)}};
vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('const PET_POSES'),source.indexOf('function invokeDesktop')),ctx);
const tick=()=>{const [id,fn]=timers.entries().next().value;timers.delete(id);fn();};
async function test(){
  const wave=ctx.playPetInteraction(['hello','nod','idle'],380);await new Promise(setImmediate);
  assert.equal($('petCharacter').dataset.frame,'hello');assert.equal($('brandMonkey').dataset.frame,'hello');
  tick();assert.equal($('brandMonkey').dataset.frame,'nod');tick();tick();await wave;
  assert.equal(timers.size,0);assert.equal($('petCharacter').dataset.frame,'idle');
  const pending=ctx.playPetInteraction(['hello','peek'],380);await new Promise(setImmediate);
  ctx.stopPetInteraction();await pending;assert.equal(timers.size,0);assert.equal($('brandMonkey').dataset.frame,'idle');
  reduced=true;await ctx.playPetInteraction(['hello']);assert.equal(timers.size,0);
  assert.equal((html.match(/gold-chain-monkey.png/g)||[]).length,1,'boss lives in dashboard header');
  assert.equal((html.match(/banana-tree.png/g)||[]).length,1,'desktop entry is a fruit tree');
  assert.ok(!html.includes('zinx-monkey-imagegen-v2.png'),'previous mascot asset is preserved outside the active entry');
  assert.equal((html.match(/class="tree-fruit" hidden/g)||[]).length,5,'bounded fruit overlay');
  const tree=fs.readFileSync(path.join(root,'shell/assets/monkey-banana-2026-09-07/banana-tree.png'));assert.equal(tree[25],6,'tree retains alpha');
  assert.ok(!/zinx-monkey-left-.*png|data-pet-frame/.test(html+source));
  assert.equal(png.subarray(1,4).toString(),'PNG');assert.equal(png[25],6,'RGBA original retains alpha');
  assert.ok(png.readUInt32BE(16)>=512 && png.readUInt32BE(20)>=512);
  assert.ok(!(html+source+css).includes('zinx-monkey.svg'));
  assert.match(css,/@media\(prefers-reduced-motion:reduce\).*animation:none!important/);
  assert.match(css,/\.monkey-art\[data-frame=hello\] img/);
  assert.ok(!css.includes('pet-working'),'remove the old whole-body continuous bounce');
  assert.match(html,/class="tree-companion"><span class="tree-monkey-sprite"/);
  assert.match(source,/petCharacter"\)\.dataset\.running=String\(activity\.running\)/);
  assert.match(css,/\.banana-tree-art\[data-running=true\] \.tree-companion\{display:block;animation:branch-peek var\(--tree-cycle\)/);
  assert.match(css,/\.tree-companion\{display:none/);
  assert.ok(css.includes('html[data-page-hidden=true] .tree-companion'));
  assert.ok(css.includes('.pet-mode[data-mode=compact] .tree-companion'));
  assert.match(css,/@media\(prefers-reduced-motion:reduce\).*\.tree-companion\{display:none!important\}/);
  const atlas=fs.readFileSync(path.join(root,'shell/assets/monkey-run-2026-09-07/run-atlas.png'));
  assert.equal(atlas[25],6);assert.equal(atlas.readUInt32BE(16),256);assert.equal(atlas.readUInt32BE(20),64);
  const frameQA=JSON.parse(fs.readFileSync(path.join(root,'shell/assets/monkey-run-2026-09-07/frame-qa.json')));
  assert.equal(frameQA.frames.length,4);assert.ok(frameQA.frames.every(f=>f.marker_pixels===0&&f.key_pixels===0));
}
test().then(()=>console.log('PASS: ImageGen boss/tree roles, preserved alpha, pose sequence, cancellation, reduced motion and bounded fruit overlay')).catch(e=>{console.error(e);process.exitCode=1;});
