const assert=require('node:assert/strict');
const {harvestState,growthState,render,renderGrowth,activityState}=require('../shell/banana-tree.js');
assert.deepEqual(harvestState(0,true),{count:0,visible:0,connected:true});
assert.deepEqual(harvestState(3,true),{count:3,visible:3,connected:true});
assert.deepEqual(harvestState(19,true),{count:19,visible:5,connected:true});
assert.equal(harvestState(-2,true).visible,0);assert.equal(harvestState(NaN,true).visible,0);
const root={dataset:{},children:Array.from({length:5},()=>({hidden:true}))};
render(root,4,true);assert.equal(root.children.filter(f=>!f.hidden).length,4);
render(root,1,true);assert.equal(root.children.filter(f=>!f.hidden).length,1,'harvesting reduces fruit');
render(root,0,true);assert.equal(root.children.filter(f=>!f.hidden).length,0,'empty tree after reading');
render(root,12,false);assert.equal(root.dataset.connected,'false','stale fruit is visually muted');assert.equal(root.dataset.count,'12','exact count separate from bounded decoration');
assert.deepEqual(render(null,2,true),harvestState(2,true));
assert.equal(activityState(2,3,true).running,true,'pending bananas do not mask running work');
assert.equal(activityState(2,3,true).state,'completed','fruit state remains independently readable');
assert.equal(activityState(2,3,true).label,'2 根香蕉待收 · 3 项任务进行中');
assert.equal(activityState(0,1,true).running,true,'an empty tree can be working');
assert.equal(activityState(2,0,true).running,false,'last task ending stops the companion even when fruit remains');
assert.equal(activityState(2,3,false).running,false,'offline evidence never animates stale work');
assert.equal(activityState(0,0,true).state,'idle');
for(const count of [-1,NaN,Infinity,undefined,'3'])assert.equal(activityState(0,count,true).running,false);
assert.deepEqual(growthState(0,true),{count:0,visible:0,connected:true});
assert.deepEqual(growthState(2,true),{count:2,visible:2,connected:true});
assert.deepEqual(growthState(19,true),{count:19,visible:3,connected:true});
assert.deepEqual(growthState(3,false),{count:0,visible:0,connected:false});
for(const count of [-1,NaN,Infinity,undefined,'3'])assert.equal(growthState(count,true).visible,0);
assert.equal(growthState(2.9,true).visible,2);
const growth={dataset:{},children:Array.from({length:3},()=>({hidden:true}))};
render(root,2,true);renderGrowth(growth,2,true);
assert.equal(root.children.filter(f=>!f.hidden).length,2,'ripe and green fruit coexist');
assert.equal(growth.children.filter(f=>!f.hidden).length,2);
render(root,3,true);renderGrowth(growth,1,true);
assert.equal(root.children.filter(f=>!f.hidden).length,3,'a new result adds ripe fruit');
assert.equal(growth.children.filter(f=>!f.hidden).length,1,'finished work removes green fruit');
render(root,0,true);renderGrowth(growth,1,true);
assert.equal(growth.children.filter(f=>!f.hidden).length,1,'reading every result keeps live work visible');
renderGrowth(growth,0,true);assert.ok(growth.children.every(f=>f.hidden),'last task ending clears green fruit');
renderGrowth(growth,20,true);assert.equal(growth.dataset.count,'20');assert.equal(growth.children.filter(f=>!f.hidden).length,3);
renderGrowth(growth,20,false);assert.ok(growth.children.every(f=>f.hidden),'offline clears stale green work');
assert.deepEqual(renderGrowth(null,2,true),growthState(2,true));
const fs=require('node:fs'),path=require('node:path'),read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
for(const p of ['shell/index.html']){
  assert.equal((read(p).match(/class="tree-green-fruit" hidden/g)||[]).length,3,'bounded, initially hidden green fruit in '+p);
}
const css=read('shell/styles.css');
assert.match(css,/\.tree-green-fruit\{--fruit-size:10px;[^}]*background:var\(--banana-green-image\)/);
assert.match(css,/\.tree-fruit\{--fruit-size:16px;/);
assert.match(css,/\.banana-tree-art\[data-running=true\] :is\(\.tree-harvest,\.tree-growth\)\{animation:harvest-settle var\(--tree-cycle\)/,'live work alone enables synchronized fruit response');
console.log('PASS: bounded green/ripe fruit coexist; completion, reading, idle and offline keep fruit and runtime consistent');
