const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root=require('node:path').join(__dirname,'..'),read=p=>fs.readFileSync(require('node:path').join(root,p),'utf8');
const source=read('shell/app.js'),html=read('shell/index.html'),native=read('desktop_shell/src-tauri/src/lib.rs');
for(const obsolete of ['newTaskButton','newTaskDialog','startTask','openNew','workspaceType','categoryFilter','/api/tasks','/api/route','work-twin-new-task']){
  assert.ok(!(html+source).includes(obsolete),'remove obsolete entry '+obsolete);
}
assert.ok(!(html+source).includes('searchInput'),'task search is removed from markup and runtime');
assert.ok(!html.includes('搜索'),'settings and tooltips only describe the remaining animation preference');
assert.ok(!native.includes('pet-new-task'));assert.ok(!native.includes('set_pet_expanded'));
const config=JSON.parse(read('desktop_shell/src-tauri/tauri.conf.json'));
assert.equal(config.productName,'Monkex');
assert.equal(config.app.windows[0].title,'Monkex');
assert.equal(config.identifier,'com.zin.work-twin','rename preserves app data identity');
assert.equal(config.app.windows[0].skipTaskbar,true,'Windows window stays out of the taskbar');
assert.match(read('desktop_shell/src-tauri/Info.plist'),/<key>LSUIElement<\/key>\s*<true\/>/,'macOS launches without a Dock tile');
assert.match(native,/ActivationPolicy::Accessory/);
assert.match(read('desktop_shell/src-tauri/permissions/work-twin.toml'),/commands.allow = \["start_window_drag", "move_pet_window"\]/,'captured tree movement has native IPC permission');
assert.ok(JSON.parse(read('desktop_shell/src-tauri/capabilities/default.json')).permissions.includes('allow-start-window-drag'));
assert.ok(!html.includes('petDragHandle'),'whole tree replaces the narrow drag handle');
assert.match(native,/"pet-quit" => app.exit\(0\)/,'native context menu exits the app');
assert.match(html,/<title>Monkex<\/title>/);
assert.match(html,/id="viewHeading"[^>]*>Monkex<\/span>/);
assert.match(html,/id="petShell"[^>]*aria-label="Monkex"/);
assert.ok(native.includes('"退出 Monkex"'));
const brandSurfaces=[html,native,JSON.stringify(config)];
for(const surface of brandSurfaces) assert.ok(!surface.includes('猴克斯'),'product surfaces use the single Monkex name');
assert.ok(config.bundle.icon.includes('icons/monkex-giant-banana-v2/icon.icns'),'desktop launcher uses the leafy monkey hugging one giant banana');
const iconData=fs.readFileSync(require('node:path').join(root,'desktop_shell/src-tauri/icons/monkex-giant-banana-v2/128x128.png'));
assert.equal(iconData.readUInt32BE(16),128);assert.equal(iconData.readUInt32BE(20),128);
assert.ok(html.includes('/gold-chain-monkey.png'),'dashboard portrait keeps its existing artwork');
assert.ok(html.includes('/banana-tree.png'),'live tree keeps its existing artwork');
for(const icon of config.bundle.icon) assert.ok(fs.existsSync(require('node:path').join(root,'desktop_shell/src-tauri',icon)));
const reopen=native.slice(native.indexOf('if matches!(event, tauri::RunEvent::Reopen'));
assert.match(reopen,/set_window_mode\(&window, true\)/,'reopening the app expands the existing board');
assert.match(reopen,/expanded: true/);assert.match(reopen,/window\.set_focus\(\)/);
assert.match(native,/window\.on_window_event/);
assert.match(native,/tauri::WindowEvent::Focused\(focused\)/);
assert.match(native,/work-twin-window-focus/);
assert.match(native,/if view == "compact" && was_collapsed\s*\{\s*window\.set_focus\(\)/,'only opening acquires focus; live resizing preserves other app focus');
assert.match(source,/addEventListener\("work-twin-window-focus",onWindowFocus\)/);
assert.ok(!html.includes('feed-footer'),'footer controls are removed');
assert.match(html,/id="pinButton"[^>]*aria-pressed="false"[^>]*><svg/);
for(const removed of ['boardSettings','playFeedbackToggle','setSettings'])assert.ok(!(html+source).includes(removed),'remove obsolete settings '+removed);
assert.match(html,/<div id="greetMonkey"/,'avatar is a display and weekly counter without an empty menu');
const elements=new Map(),styles={},timers=new Map(),modes=[],writes=[],calls=[];let timerId=0;
const $=id=>{if(!elements.has(id))elements.set(id,{hidden:true,value:'',offsetHeight:112,focus(){this.focused=true;},setAttribute(k,v){this[k]=v;}});return elements.get(id);};
const state={mode:'compact',petMode:true,pinned:false,boardSize:0,selectionRevision:0,navigation:{pending:null,navigate:async()=>true}};
const ctx={state,$,clearTimeout:id=>timers.delete(id),setTimeout:(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId;},
  document:{documentElement:{style:{setProperty:(k,v)=>styles[k]=v}}},localStorage:{setItem:(...args)=>writes.push(args)},
  filtered:()=>Array.from({length:3}),renderList(){},mode:value=>{state.mode=value;modes.push(value);},
  invokeDesktop:(name,args)=>{calls.push({name,args});return Promise.resolve();}};
vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('function boardHeight('),source.indexOf('function bind(')),ctx);
(async()=>{
  assert.equal(ctx.boardHeight(0),180);assert.equal(ctx.boardHeight(3),230);
  assert.equal(ctx.boardHeight(7),414);assert.equal(ctx.boardHeight(100),420);
  assert.equal(ctx.boardHeight(3,112),342);
  ctx.syncBoardSize();assert.equal(styles['--board-height'],'230px');
  assert.equal(calls[0].args.height,230);ctx.syncBoardSize();assert.equal(calls.length,1,'unchanged size has no native IPC');
  ctx.togglePin();assert.equal($('pinButton')['aria-pressed'],'true');assert.match($('pinButton').title,/拔起/);
  assert.deepEqual(writes[0],['twin-pinned','true']);
  await ctx.selectThread('a');assert.equal(timers.size,0,'pinned board stays expanded');
  ctx.togglePin();await ctx.selectThread('a');assert.equal(timers.size,1);
  const [id,timer]=[...timers][0];assert.equal(timer.ms,1200);timers.delete(id);timer.fn();
  assert.equal(modes.at(-1),'collapsed');
  state.mode='compact';await ctx.selectThread('a');ctx.togglePin();assert.equal(timers.size,0,'pin cancels an armed collapse');
  ctx.togglePin();state.navigation.navigate=async()=>false;await ctx.selectThread('a');assert.equal(timers.size,0,'failed open stays visible');
  state.navigation.navigate=async()=>true;$('systemBanner').hidden=false;
  await ctx.selectThread('a');assert.equal(timers.size,0,'failed read receipt stays visible');
  $('systemBanner').hidden=true;
  state.petMode=false;await ctx.selectThread('a');assert.equal(timers.size,0,'browser preview stays open');
  const lost={detail:{focused:false}};
  ctx.onWindowFocus(lost);assert.equal(state.mode,'compact','browser stays open');
  state.petMode=true;state.pinned=true;ctx.onWindowFocus(lost);assert.equal(state.mode,'compact','pinned board survives native blur');
  state.pinned=false;ctx.onWindowFocus({detail:{focused:true}});assert.equal(state.mode,'compact','gaining focus keeps board open');
  ctx.onWindowFocus({});assert.equal(state.mode,'compact','DOM control focus is not native focus loss');
  state.navigation.pending='a';ctx.onWindowFocus(lost);assert.equal(state.mode,'compact','navigation keeps ownership of acknowledgement and failure feedback');
  state.navigation.pending=null;ctx.onWindowFocus(lost);assert.equal(state.mode,'collapsed','unpinned board collapses on native blur');
  const collapsedCalls=modes.length;ctx.onWindowFocus(lost);assert.equal(modes.length,collapsedCalls,'collapsed tree ignores redundant blur');
  const tree=$('petLauncher');let captured=null;
  tree.setPointerCapture=id=>{captured=id;};tree.hasPointerCapture=id=>captured===id;tree.releasePointerCapture=()=>{captured=null;};
  ctx.stopPetInteraction=()=>{};
  ctx.bindPetDrag();
  const pointer=(x,y,extra={})=>({button:0,buttons:1,pointerId:1,clientX:x,clientY:y,screenX:x,screenY:y,preventDefault(){},...extra});
  const beforeDrag=calls.length;
  tree.onpointerdown(pointer(35,35));tree.onpointermove(pointer(36,36));tree.onpointerup();tree.onclick({detail:1});
  assert.equal(calls.length,beforeDrag);assert.equal(state.mode,'compact','small motion remains a click');
  state.mode='collapsed';tree.onpointerdown(pointer(35,35,{buttons:0}));tree.onpointermove(pointer(42,35,{buttons:0}));tree.onpointermove(pointer(80,35,{buttons:0}));
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(calls.length,beforeDrag+2);assert.equal(calls.at(-1).name,'move_pet_window');assert.equal(captured,1);
  assert.equal(calls.at(-2).args.dx,7);assert.equal(calls.at(-1).args.dx,38);
  tree.onpointerup();assert.equal(captured,null);tree.onclick({detail:1,preventDefault(){}});assert.equal(state.mode,'collapsed','drag release does not expand');
  tree.onclick({detail:0});assert.equal(state.mode,'compact','keyboard activation still opens after a drag');
  tree.onpointerdown(pointer(35,35,{button:2}));assert.equal(captured,null,'right click keeps native menu available');
  tree.onpointerdown(pointer(35,35));tree.onpointercancel();tree.onpointermove(pointer(42,35));assert.equal(calls.length,beforeDrag+2,'canceled pointer never drags');
  console.log('PASS: observer-only entry, graphic pin, bounded adaptive sizing, removed settings, native focus collapse and navigation failure preservation');
})().catch(error=>{console.error(error);process.exitCode=1;});
