const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../shell/app.js'),'utf8');
const native=fs.readFileSync(require('node:path').join(__dirname,'../desktop_shell/src-tauri/src/lib.rs'),'utf8');
const permission=fs.readFileSync(require('node:path').join(__dirname,'../desktop_shell/src-tauri/permissions/set-pet-view.toml'),'utf8');
assert.match(permission,/"pet_pointer_inside"/,'the packaged webview can read membership in its own window');
assert.match(native,/generate_handler!\[[\s\S]*?pet_pointer_inside,/,'the native command is registered');
assert.match(source,/if\(state.petMode&&window\.__TAURI__\?\.core\?\.invoke\)pollNativePointer\(\)/,'boot starts background-window tracking');
assert.match(source,/"pagehide",stopHoverTracking/,'unload cancels pending native sampling');
const timers=new Map();let next=0;
const state={petMode:true,mode:'collapsed',pinned:false,pointerInside:false,nativePointerInside:null,petDragging:false,navigation:{pending:null}};
const ctx={state,clearTimeout:id=>timers.delete(id),setTimeout:(fn,ms)=>{timers.set(++next,{fn,ms});return next;},mode:value=>{state.mode=value;},console};
vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('function cancelAutoCollapse('),source.indexOf('function syncPin(')),ctx);
const fire=ms=>{for(const [id,timer]of [...timers])if(timer.ms===ms){timers.delete(id);timer.fn();}};
assert.equal(typeof ctx.onNativePointer,'function','background hover must have a native pointer path independent of DOM enter events');
ctx.onNativePointer(true);assert.equal(state.mode,'collapsed','entry allows a brief drag intent interval');
fire(180);assert.equal(state.mode,'compact','native pointer entry opens without a DOM mouseenter or focus event');
ctx.onNativePointer(false);fire(300);assert.equal(state.mode,'collapsed','native exit collapses without a DOM pointerleave');
ctx.onNativePointer(true);state.petDragging=true;fire(180);assert.equal(state.mode,'collapsed','press-and-drag keeps the tree collapsed');state.petDragging=false;
ctx.onNativePointer(true);assert.equal(timers.size,0,'drag release waits for a new entry');
ctx.onNativePointer(false);ctx.onNativePointer(true);fire(180);assert.equal(state.mode,'compact');
state.mode='collapsed';ctx.onNativePointer(true);fire(180);assert.equal(state.mode,'collapsed','manual collapse stays closed until pointer exit/reentry');
ctx.onNativePointer(false);ctx.onNativePointer(true);fire(180);state.pinned=true;
ctx.onNativePointer(false);fire(300);assert.equal(state.mode,'compact','pin retains the board on native exit');
state.pinned=false;ctx.onNativePointer(true);ctx.onNativePointer(false);ctx.onNativePointer(true);fire(300);assert.equal(state.mode,'compact','returning cancels collapse');
console.log('PASS: native-only hover entry/exit, drag intent, manual collapse, reentry and pin');
(async()=>{
  timers.clear();state.hoverTrackingStopped=false;
  let resolveSample,calls=0;
  ctx.invokeDesktop=()=>{calls++;return new Promise(resolve=>{resolveSample=resolve;});};
  const pending=ctx.pollNativePointer();
  assert.equal(calls,1);assert.equal(timers.size,0,'sampling waits for IPC completion before scheduling another call');
  ctx.stopHoverTracking();resolveSample(true);await pending;
  assert.equal(timers.size,0,'unload prevents late IPC from reopening the board or restarting polling');
  state.hoverTrackingStopped=false;state.nativePointerInside=null;state.mode='collapsed';
  ctx.invokeDesktop=async()=>true;await ctx.pollNativePointer();fire(180);
  assert.equal(state.mode,'compact','the native IPC result reaches the hover state machine');
  assert.ok([...timers.values()].some(timer=>timer.ms===120));ctx.stopHoverTracking();
  console.log('PASS: serial native sampling, IPC-to-hover integration and unload race');
})().catch(error=>{console.error(error);process.exitCode=1;});
